/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.24.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./ArtDealer.types";
import * as _1 from "./ArtDealer.client";
import * as _2 from "./ArtDealer.react-query";
import * as _3 from "./Governance.types";
import * as _4 from "./Governance.client";
import * as _5 from "./Governance.react-query";
import * as _6 from "./Identityservice.types";
import * as _7 from "./Identityservice.client";
import * as _8 from "./Identityservice.react-query";
export namespace contracts {
  export const ArtDealer = { ..._0,
    ..._1,
    ..._2
  };
  export const Governance = { ..._3,
    ..._4,
    ..._5
  };
  export const Identityservice = { ..._6,
    ..._7,
    ..._8
  };
}