/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.33.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./DaoMembers.types";
import * as _1 from "./DaoMembers.client";
import * as _2 from "./DaoMembers.react-query";
import * as _3 from "./DaoMultisig.types";
import * as _4 from "./DaoMultisig.client";
import * as _5 from "./DaoMultisig.react-query";
import * as _6 from "./Governance.types";
import * as _7 from "./Governance.client";
import * as _8 from "./Governance.react-query";
import * as _9 from "./Identityservice.types";
import * as _10 from "./Identityservice.client";
import * as _11 from "./Identityservice.react-query";
export namespace contracts {
  export const DaoMembers = { ..._0,
    ..._1,
    ..._2
  };
  export const DaoMultisig = { ..._3,
    ..._4,
    ..._5
  };
  export const Governance = { ..._6,
    ..._7,
    ..._8
  };
  export const Identityservice = { ..._9,
    ..._10,
    ..._11
  };
}