/**
* This file was automatically generated by @cosmwasm/ts-codegen@0.10.0.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import * as _0 from "./Dao.types";
import * as _1 from "./Dao.client";
export namespace contracts {
  export const Dao = { ..._0,
    ..._1
  };
}